"use client";

import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { AnalysisProgress } from "@/components/analysis-progress";
import { AiExplanationPanel } from "@/components/ai-explanation-panel";
import { ProductGuidancePanel } from "@/components/product-guidance-panel";
import { RagQuestionPanel } from "@/components/rag-question-panel";
import { useLocale } from "@/components/providers/locale-provider";
import { getAiExplanation } from "@/services/ai-explanation";
import { precheckEligibility } from "@/services/eligibility";
import { getPersonalizedGuidance, getProductGuidance } from "@/services/guidance";
import { getProduct } from "@/services/product";
import type { EligibilityResult, EligibilityRuleDetail, EligibilityStatus } from "@/types/eligibility";
import type { ProductRule } from "@/types/product";

type Tab = "precheck" | "evidence" | "documents" | "steps" | "official";
const copy = {
  ko: { back: "상품 목록", tabs: { precheck: "사전진단", evidence: "판단 근거", documents: "필요서류", steps: "신청 절차", official: "공식 정보" }, run: "내 프로필로 사전자격 확인", rerun: "다시 진단", checking: "공개조건 비교 중...", description: "저장된 임시 프로필과 검수된 공식 Rule을 비교합니다.", noProfile: "임시 프로필이 없거나 만료되었습니다.", create: "프로필 입력", error: "진단을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.", status: { PUBLIC_CONDITIONS_MET: "공개조건 충족", NEED_BANK_CONFIRMATION: "은행 확인 필요", PUBLIC_CONDITIONS_NOT_MET: "공개조건 미충족", INSUFFICIENT_INFORMATION: "정보 부족" }, final: "최종 가입승인이 아닙니다.", passed: "충족 조건", failed: "미충족 조건", external: "은행 확인 조건", unknown: "공개되지 않은 조건", insufficient: "부족한 정보", empty: "해당 항목이 없습니다.", source: "출처", checked: "확인일", locator: "근거 위치", ruleTitle: "검수된 상품조건", noRules: "현재 유효한 승인 Rule이 없습니다.", required: "필수", optional: "선택", summary: "상품 요약", public: "공개조건", additional: "추가 확인 조건", base: "정보 기준일", officialLink: "공식 페이지 열기" },
  en: { back: "Products", tabs: { precheck: "Pre-check", evidence: "Evidence", documents: "Documents", steps: "Application steps", official: "Official information" }, run: "Check eligibility with my profile", rerun: "Check again", checking: "Comparing public conditions...", description: "Compares your saved temporary profile with reviewed official Rules.", noProfile: "Your temporary profile is missing or expired.", create: "Create profile", error: "The check could not be completed. Please try again shortly.", status: { PUBLIC_CONDITIONS_MET: "Public conditions met", NEED_BANK_CONFIRMATION: "Bank confirmation needed", PUBLIC_CONDITIONS_NOT_MET: "Public conditions not met", INSUFFICIENT_INFORMATION: "Insufficient information" }, final: "This is not final approval.", passed: "Conditions met", failed: "Conditions not met", external: "Bank checks", unknown: "Unpublished conditions", insufficient: "Missing information", empty: "No items in this section.", source: "Source", checked: "Checked", locator: "Evidence location", ruleTitle: "Reviewed product conditions", noRules: "There are no currently effective approved Rules.", required: "Required", optional: "Optional", summary: "Product summary", public: "Public conditions", additional: "Additional checks", base: "Information date", officialLink: "Open official page" },
  vi: { back: "Danh sách sản phẩm", tabs: { precheck: "Kiểm tra sơ bộ", evidence: "Căn cứ", documents: "Giấy tờ", steps: "Các bước đăng ký", official: "Thông tin chính thức" }, run: "Kiểm tra bằng hồ sơ của tôi", rerun: "Kiểm tra lại", checking: "Đang so sánh điều kiện công khai...", description: "So sánh hồ sơ tạm thời với Rule chính thức đã kiểm duyệt.", noProfile: "Hồ sơ tạm thời không tồn tại hoặc đã hết hạn.", create: "Nhập hồ sơ", error: "Không thể hoàn tất kiểm tra. Vui lòng thử lại sau.", status: { PUBLIC_CONDITIONS_MET: "Đáp ứng điều kiện công khai", NEED_BANK_CONFIRMATION: "Cần ngân hàng xác nhận", PUBLIC_CONDITIONS_NOT_MET: "Không đáp ứng điều kiện công khai", INSUFFICIENT_INFORMATION: "Thiếu thông tin" }, final: "Đây không phải phê duyệt cuối cùng.", passed: "Điều kiện đã đạt", failed: "Điều kiện chưa đạt", external: "Ngân hàng cần xác nhận", unknown: "Điều kiện không công khai", insufficient: "Thông tin còn thiếu", empty: "Không có mục nào.", source: "Nguồn", checked: "Ngày xác nhận", locator: "Vị trí căn cứ", ruleTitle: "Điều kiện sản phẩm đã duyệt", noRules: "Không có Rule đã duyệt đang có hiệu lực.", required: "Bắt buộc", optional: "Tùy chọn", summary: "Tóm tắt sản phẩm", public: "Điều kiện công khai", additional: "Điều kiện cần xác nhận", base: "Ngày thông tin", officialLink: "Mở trang chính thức" },
} as const;
const tabs: Tab[] = ["precheck", "evidence", "documents", "steps", "official"];
const statusStyle: Record<EligibilityStatus, string> = { PUBLIC_CONDITIONS_MET: "border-emerald-300 bg-emerald-50 text-emerald-950", NEED_BANK_CONFIRMATION: "border-amber-300 bg-amber-50 text-amber-950", PUBLIC_CONDITIONS_NOT_MET: "border-rose-300 bg-rose-50 text-rose-950", INSUFFICIENT_INFORMATION: "border-slate-300 bg-slate-100 text-slate-900" };
const statusIcon: Record<EligibilityStatus, string> = { PUBLIC_CONDITIONS_MET: "●", NEED_BANK_CONFIRMATION: "▲", PUBLIC_CONDITIONS_NOT_MET: "×", INSUFFICIENT_INFORMATION: "○" };

export function ProductDetailDashboard() {
  const { locale } = useLocale(); const text = copy[locale]; const params = useParams<{ id: string }>(); const search = useSearchParams(); const id = Number(params.id);
  const requestedTab = search.get("tab") as Tab | null;
  const [activeTab, setActiveTab] = useState<Tab>(requestedTab && tabs.includes(requestedTab) ? requestedTab : "precheck");
  const [missingProfile, setMissingProfile] = useState(false);
  const product = useQuery({ queryKey: ["product", id], queryFn: () => getProduct(id), enabled: Number.isFinite(id) });
  const guidance = useQuery({ queryKey: ["product-guidance", id, locale], queryFn: () => getProductGuidance(id, locale), enabled: Number.isFinite(id) });
  const precheck = useMutation({ mutationFn: precheckEligibility, onError: (error: Error) => setMissingProfile(/profile|expired/i.test(error.message)) });
  const explanation = useMutation({ mutationFn: getAiExplanation });
  const personalized = useMutation({ mutationFn: ({ productId, profileSessionId }: { productId: number; profileSessionId: string }) => getPersonalizedGuidance(productId, profileSessionId) });
  function run() { const profileSessionId = localStorage.getItem("visafyProfileSessionId"); if (!profileSessionId) { setMissingProfile(true); return; } setMissingProfile(false); explanation.reset(); personalized.reset(); const request = { profileSessionId, productId: id }; precheck.mutate(request, { onSuccess: () => { explanation.mutate(request); personalized.mutate(request); } }); }
  if (product.isLoading) return <main className="mx-auto max-w-6xl px-6 py-12"><div className="h-60 animate-pulse rounded-3xl bg-slate-200" /></main>;
  if (product.isError || !product.data) return <main className="mx-auto max-w-6xl px-6 py-12 text-rose-700">{product.error?.message ?? "Product not found"}</main>;
  const item = product.data; const currentGuidance = personalized.data ?? guidance.data;
  const evidenceRequested = Boolean(precheck.data); const evidenceDone = evidenceRequested && !explanation.isPending && !personalized.isPending;
  return <main className="mx-auto max-w-6xl px-5 py-10 sm:px-6 sm:py-12">
    <Link className="text-sm font-bold text-blue-700" href="/products">← {text.back}</Link>
    <header className="mt-5 rounded-3xl bg-slate-950 p-7 text-white sm:p-10"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{item.diagnosisStatus}</span><span className="text-sm text-slate-300">{item.institution}</span></div><h1 className="mt-5 text-3xl font-bold sm:text-4xl">{item.productName}</h1><p className="mt-4 max-w-3xl leading-7 text-slate-300">{item.description}</p></header>
    <nav className="sticky top-2 z-20 mt-6 overflow-x-auto rounded-2xl border bg-white/95 p-2 shadow-sm backdrop-blur" aria-label="Product detail tabs" role="tablist"><div className="flex min-w-max gap-1">{tabs.map((tab) => <button aria-selected={activeTab === tab} className={`rounded-xl px-4 py-3 text-sm font-bold transition ${activeTab === tab ? "bg-blue-700 text-white" : "text-slate-600 hover:bg-slate-100"}`} key={tab} onClick={() => setActiveTab(tab)} role="tab" type="button">{text.tabs[tab]}</button>)}</div></nav>

    {activeTab === "precheck" ? <section className="mt-6" role="tabpanel"><div className="rounded-3xl bg-gradient-to-br from-blue-950 to-slate-950 p-7 text-white sm:p-9"><div className="flex flex-wrap items-center justify-between gap-5"><div><h2 className="text-2xl font-bold">{text.run}</h2><p className="mt-2 text-sm text-slate-300">{text.description}</p></div><button className="rounded-xl bg-teal-400 px-5 py-3 font-black text-slate-950 disabled:opacity-60" disabled={precheck.isPending} onClick={run}>{precheck.isPending ? text.checking : precheck.data ? text.rerun : text.run}</button></div></div>
      {precheck.isPending ? <div className="mt-5"><AnalysisProgress /></div> : null}
      {precheck.data && !evidenceDone ? <div className="mt-5"><AnalysisProgress recommendationDone evidenceRequested evidenceDone={false} /></div> : null}
      {missingProfile ? <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-amber-50 p-5 text-amber-950"><p>{text.noProfile}</p><Link className="rounded-lg bg-amber-900 px-4 py-2 text-sm font-bold text-white" href="/profile">{text.create} →</Link></div> : null}
      {precheck.isError && !missingProfile ? <p className="mt-5 rounded-2xl bg-rose-50 p-5 text-rose-800">{text.error}</p> : null}
      {precheck.data ? <PrecheckResult result={precheck.data} rules={item.rules} sourceTitle={item.sourceTitle} text={text} /> : null}
      {precheck.data ? <div id="bank-inquiry"><AiExplanationPanel data={explanation.data} loading={explanation.isPending} error={explanation.isError} /></div> : null}
    </section> : null}
    {activeTab === "evidence" ? <section className="mt-6" role="tabpanel"><RuleEvidence rules={item.rules} sourceTitle={item.sourceTitle} text={text} /><RagQuestionPanel productId={item.id} rules={item.rules} /></section> : null}
    {activeTab === "documents" ? <section className="mt-6" role="tabpanel"><ProductGuidancePanel guidance={currentGuidance} sourceUrl={item.sourceUrl} loading={guidance.isLoading || personalized.isPending} view="documents" /></section> : null}
    {activeTab === "steps" ? <section className="mt-6" role="tabpanel"><ProductGuidancePanel guidance={currentGuidance} sourceUrl={item.sourceUrl} loading={guidance.isLoading || personalized.isPending} view="steps" /></section> : null}
    {activeTab === "official" ? <section className="mt-6 grid gap-5 sm:grid-cols-2" role="tabpanel"><Info title={text.summary} body={item.targetSummary} /><Info title={text.public} body={item.publicConditions} /><Info title={text.additional} body={item.additionalConditions} /><article className="rounded-2xl border bg-white p-6"><h2 className="font-bold">{item.sourceTitle}</h2><p className="mt-3 text-sm text-slate-500">{text.base}: {item.informationBaseDate}</p><a className="mt-5 inline-flex rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white" href={item.sourceUrl} rel="noreferrer" target="_blank">{text.officialLink} ↗</a></article></section> : null}
    <p className="mt-8 rounded-xl bg-amber-50 p-4 text-center text-sm font-bold text-amber-950">{text.final}</p>
  </main>;
}

function PrecheckResult({ result, rules, sourceTitle, text }: { result: EligibilityResult; rules: ProductRule[]; sourceTitle: string; text: (typeof copy)[keyof typeof copy] }) { return <section className="mt-6 space-y-5" aria-live="polite"><header className={`rounded-2xl border p-6 ${statusStyle[result.status]}`}><p className="text-xs font-black tracking-widest">ELIGIBILITY PRE-CHECK</p><h2 className="mt-2 text-2xl font-bold"><span className="mr-2">{statusIcon[result.status]}</span>{text.status[result.status]}</h2><p className="mt-3 text-sm font-bold">{text.final}</p></header><div className="grid gap-5 lg:grid-cols-2"><ResultGroup title={text.passed} items={result.passedRules} tone="emerald" rules={rules} sourceTitle={sourceTitle} text={text} /><ResultGroup title={text.failed} items={result.failedRules} tone="rose" rules={rules} sourceTitle={sourceTitle} text={text} /><ResultGroup title={text.external} items={result.externalChecks} tone="amber" rules={rules} sourceTitle={sourceTitle} text={text} /><ResultGroup title={text.unknown} items={result.unknownRules} tone="violet" rules={rules} sourceTitle={sourceTitle} text={text} /><ResultGroup title={text.insufficient} items={result.insufficientReasons} tone="slate" rules={rules} sourceTitle={sourceTitle} text={text} /></div><p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{result.disclaimer}</p></section>; }
const tones = { emerald: "border-emerald-200 bg-emerald-50", rose: "border-rose-200 bg-rose-50", amber: "border-amber-200 bg-amber-50", violet: "border-violet-200 bg-violet-50", slate: "border-slate-200 bg-slate-50" } as const;
function ResultGroup({ title, items, tone, rules, sourceTitle, text }: { title: string; items: EligibilityRuleDetail[]; tone: keyof typeof tones; rules: ProductRule[]; sourceTitle: string; text: (typeof copy)[keyof typeof copy] }) { return <section className={`rounded-2xl border p-5 ${tones[tone]}`}><div className="flex justify-between"><h3 className="font-bold">{title}</h3><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold">{items.length}</span></div>{items.length ? <div className="mt-4 space-y-3">{items.map((detail, index) => { const rule = rules.find((candidate) => candidate.id === detail.ruleId || candidate.ruleKey === detail.key); return <article className="rounded-xl bg-white p-4 shadow-sm" key={`${detail.key}-${index}`}><p className="text-sm font-semibold leading-6">{detail.message}</p>{detail.sourceExcerpt ? <blockquote className="mt-2 border-l-2 pl-3 text-xs leading-5 text-slate-500">{detail.sourceExcerpt}</blockquote> : null}{detail.sourceUrl ? <div className="mt-3 text-xs text-slate-500"><a className="font-bold text-blue-700 underline" href={detail.sourceUrl} rel="noreferrer" target="_blank">{text.source}: {sourceTitle}</a>{rule?.verifiedAt ? <span> · {text.checked}: {rule.verifiedAt.slice(0, 10)}</span> : null}{detail.sourceLocator ? <p className="mt-1">{text.locator}: {detail.sourceLocator}</p> : null}</div> : null}</article>; })}</div> : <p className="mt-4 text-sm text-slate-500">{text.empty}</p>}</section>; }
function RuleEvidence({ rules, sourceTitle, text }: { rules: ProductRule[]; sourceTitle: string; text: (typeof copy)[keyof typeof copy] }) { return <section className="rounded-3xl border bg-white p-6 sm:p-8"><h2 className="text-2xl font-bold">{text.ruleTitle}</h2>{rules.length ? <div className="mt-5 grid gap-4">{rules.map((rule) => <article className="rounded-2xl bg-slate-50 p-5" key={rule.id}><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-bold text-blue-800">{rule.ruleLevel}</span><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-slate-600">{rule.mandatory ? text.required : text.optional}</span></div><p className="mt-3 font-mono text-sm font-bold">{rule.ruleKey} {rule.operator} {rule.ruleValue}</p><p className="mt-2 text-sm text-slate-700">{rule.description}</p><blockquote className="mt-3 border-l-2 border-slate-300 pl-3 text-xs leading-5 text-slate-500">{rule.sourceExcerpt}</blockquote><p className="mt-3 text-xs text-slate-500">{text.source}: {sourceTitle} · {text.checked}: {rule.verifiedAt.slice(0, 10)} · {text.locator}: {rule.sourceLocator}</p></article>)}</div> : <p className="mt-4 text-slate-500">{text.noRules}</p>}</section>; }
function Info({ title, body }: { title: string; body: string }) { return <article className="rounded-2xl border bg-white p-6"><h2 className="font-bold">{title}</h2><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{body}</p></article>; }
