"use client";

import { useMutation } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { useLocale } from "@/components/providers/locale-provider";
import type { Locale } from "@/i18n/config";
import { nationalityOptions } from "@/lib/nationalities";
import { allFinancialPurposes, financialPurposeLabel, type FinancialPurposeCode } from "@/lib/financial-purposes";
import { createProfile } from "@/services/profile";
import { cx, ui } from "@/components/ui/primitives";

const copy = {
  ko: { title: "내 금융생활 시작하기", description: "처음에는 국적·목적과 현재 준비상태만 확인합니다. 비자·소득·재직정보는 선택한 상품의 공식 Rule에 필요할 때만 요청합니다.", steps: ["언어", "국적 + 금융 목적", "현재 금융 준비상태", "상품별 추가정보", "이용 가능한 서비스"], next: "다음 단계", back: "이전", save: "내게 필요한 금융서비스 보기", saving: "금융생활 경로를 준비하고 있습니다...", nationality: "국적", chooseNationality: "실제 국적을 선택하세요", purpose: "한국에서 지금 가장 필요한 금융서비스", optional: "모르는 항목은 비워두어도 됩니다.", residenceCard: "외국인등록증·체류카드 보유", passport: "여권 보유", phone: "국내 휴대전화 보유", phoneVerify: "국내 휴대전화 본인인증 가능", account: "한국 입출금계좌 보유", credit: "한국 신용이력 보유", channel: "선호 신청채널", yes: "예", no: "아니요", unknown: "모름 / 선택 안 함", privacy: "신분증 번호, 여권번호, 계좌번호는 수집하지 않습니다. 보유 여부만 24시간 임시 저장합니다.", error: "프로필을 저장하지 못했습니다. 입력값을 확인해 주세요." },
  en: { title: "Start my financial life", description: "We first ask only your nationality, goal, and current preparation. Visa, income, and employment details are requested only when an official product Rule needs them.", steps: ["Language", "Nationality + goal", "Current preparation", "Product-specific details", "Available services"], next: "Next", back: "Back", save: "Show financial services for me", saving: "Preparing your financial journey...", nationality: "Nationality", chooseNationality: "Select your actual nationality", purpose: "What financial service do you need most in Korea?", optional: "Leave an item blank if you do not know.", residenceCard: "I have a residence card", passport: "I have a passport", phone: "I have a Korean mobile phone", phoneVerify: "I can verify with my Korean phone", account: "I have a Korean demand-deposit account", credit: "I have Korean credit history", channel: "Preferred application channel", yes: "Yes", no: "No", unknown: "Unknown / skip", privacy: "We do not collect ID, passport, or account numbers. Only possession status is stored for 24 hours.", error: "Could not save the profile. Please check your entries." },
  vi: { title: "Bắt đầu cuộc sống tài chính", description: "Ban đầu chúng tôi chỉ hỏi quốc tịch, mục tiêu và tình trạng chuẩn bị. Thông tin visa, thu nhập và việc làm chỉ được hỏi khi quy tắc chính thức của sản phẩm yêu cầu.", steps: ["Ngôn ngữ", "Quốc tịch + mục tiêu", "Tình trạng chuẩn bị", "Thông tin theo sản phẩm", "Dịch vụ có thể sử dụng"], next: "Tiếp theo", back: "Quay lại", save: "Xem dịch vụ tài chính phù hợp", saving: "Đang chuẩn bị hành trình tài chính...", nationality: "Quốc tịch", chooseNationality: "Chọn quốc tịch thực tế", purpose: "Bạn cần dịch vụ tài chính nào nhất tại Hàn Quốc?", optional: "Có thể để trống nếu chưa biết.", residenceCard: "Tôi có thẻ cư trú", passport: "Tôi có hộ chiếu", phone: "Tôi có điện thoại tại Hàn Quốc", phoneVerify: "Tôi có thể xác minh bằng điện thoại Hàn Quốc", account: "Tôi có tài khoản thanh toán tại Hàn Quốc", credit: "Tôi có lịch sử tín dụng tại Hàn Quốc", channel: "Kênh đăng ký ưu tiên", yes: "Có", no: "Không", unknown: "Không biết / bỏ qua", privacy: "Không thu thập số giấy tờ, hộ chiếu hoặc tài khoản. Chỉ lưu tình trạng sở hữu trong 24 giờ.", error: "Không thể lưu hồ sơ. Vui lòng kiểm tra thông tin." },
  zh: { title: "开始我的金融生活", description: "首先只询问您的国籍、目标和当前准备情况。只有产品的官方规则需要时，才会询问签证、收入和就业信息。", steps: ["语言", "国籍与金融目标", "当前准备情况", "产品所需信息", "可使用的服务"], next: "下一步", back: "返回", save: "查看适合我的金融服务", saving: "正在准备您的金融生活路径……", nationality: "国籍", chooseNationality: "请选择您的实际国籍", purpose: "您目前在韩国最需要哪种金融服务？", optional: "不清楚的项目可以留空。", residenceCard: "持有外国人登录证或居留卡", passport: "持有护照", phone: "持有韩国手机", phoneVerify: "可以使用韩国手机进行本人认证", account: "持有韩国活期账户", credit: "在韩国有信用记录", channel: "首选申请渠道", yes: "是", no: "否", unknown: "不清楚 / 跳过", privacy: "我们不收集证件号、护照号或账户号码，只将持有状态临时保存24小时。", error: "无法保存资料，请检查输入内容。" },
  ja: { title: "金融生活を始める", description: "最初は国籍・目的・現在の準備状況だけを確認します。ビザ・収入・雇用情報は、商品の公式ルールで必要な場合にのみお尋ねします。", steps: ["言語", "国籍と金融目的", "現在の準備状況", "商品別の追加情報", "利用可能なサービス"], next: "次へ", back: "戻る", save: "自分に必要な金融サービスを見る", saving: "金融生活の道筋を準備しています…", nationality: "国籍", chooseNationality: "実際の国籍を選択してください", purpose: "今、韓国で最も必要な金融サービスは何ですか？", optional: "わからない項目は空欄でも構いません。", residenceCard: "外国人登録証・在留カードを持っている", passport: "パスポートを持っている", phone: "韓国の携帯電話を持っている", phoneVerify: "韓国の携帯電話で本人認証ができる", account: "韓国の普通預金口座を持っている", credit: "韓国で信用履歴がある", channel: "希望する申込方法", yes: "はい", no: "いいえ", unknown: "不明 / スキップ", privacy: "身分証番号・旅券番号・口座番号は収集せず、保有状況だけを24時間保存します。", error: "プロフィールを保存できませんでした。入力内容を確認してください。" },
  th: { title: "เริ่มต้นชีวิตทางการเงินของฉัน", description: "ขั้นแรกเราจะถามเฉพาะสัญชาติ เป้าหมาย และความพร้อมในปัจจุบัน ข้อมูลวีซ่า รายได้ และการจ้างงานจะถามเฉพาะเมื่อกฎทางการของผลิตภัณฑ์กำหนด", steps: ["ภาษา", "สัญชาติและเป้าหมาย", "ความพร้อมในปัจจุบัน", "ข้อมูลเฉพาะผลิตภัณฑ์", "บริการที่ใช้ได้"], next: "ถัดไป", back: "ย้อนกลับ", save: "ดูบริการทางการเงินที่เหมาะกับฉัน", saving: "กำลังเตรียมเส้นทางการเงินของคุณ…", nationality: "สัญชาติ", chooseNationality: "เลือกสัญชาติจริงของคุณ", purpose: "ตอนนี้คุณต้องการบริการทางการเงินใดมากที่สุดในเกาหลี", optional: "หากไม่ทราบสามารถเว้นว่างได้", residenceCard: "มีบัตรประจำตัวคนต่างด้าวหรือบัตรพำนัก", passport: "มีหนังสือเดินทาง", phone: "มีโทรศัพท์มือถือในเกาหลี", phoneVerify: "ยืนยันตัวตนด้วยโทรศัพท์เกาหลีได้", account: "มีบัญชีเงินฝากในเกาหลี", credit: "มีประวัติเครดิตในเกาหลี", channel: "ช่องทางสมัครที่ต้องการ", yes: "ใช่", no: "ไม่", unknown: "ไม่ทราบ / ข้าม", privacy: "เราไม่เก็บเลขบัตรประจำตัว เลขหนังสือเดินทาง หรือเลขบัญชี และเก็บเฉพาะสถานะการมีเอกสารเป็นเวลา 24 ชั่วโมง", error: "ไม่สามารถบันทึกโปรไฟล์ได้ โปรดตรวจสอบข้อมูล" },
} as const;

export function ProfileWizard() {
  const { locale } = useLocale(); const router = useRouter(); const text = copy[locale];
  const [step, setStep] = useState(1); const [nationality, setNationality] = useState("");
  const [purpose, setPurpose] = useState<FinancialPurposeCode>("OPEN_ACCOUNT");
  const mutation = useMutation({ mutationFn: createProfile, onSuccess: (profile) => { localStorage.setItem("visafyProfileId", String(profile.id)); localStorage.setItem("visafyProfileSessionId", profile.sessionId); router.push("/products"); } });
  useEffect(() => { const saved = localStorage.getItem("visafyFinancialPurpose") as FinancialPurposeCode | null; if (saved && allFinancialPurposes.includes(saved)) setPurpose(saved); }, []);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const bank = optionalBoolean(data.get("hasKoreanBankAccount")); mutation.mutate({ nationality, financialPurpose: purpose, language: locale, birthDate: null, visaType: null, visaExpiry: null, residencyStartDate: null, occupation: null, employmentType: null, monthlyIncome: null, employmentDurationMonths: null, residentStatus: null, hasResidenceCard: optionalBoolean(data.get("hasResidenceCard")), hasPassport: optionalBoolean(data.get("hasPassport")), hasDomesticPhone: optionalBoolean(data.get("hasDomesticPhone")), canDomesticPhoneVerify: optionalBoolean(data.get("canDomesticPhoneVerify")), hasKoreanBankAccount: bank, hasBankAccount: bank, hasKoreanCreditHistory: optionalBoolean(data.get("hasKoreanCreditHistory")), preferredChannel: data.get("preferredChannel") || null, remittanceCountry: null, housingType: null, desiredAmount: null, preferredBank: null, hasExistingProductAccount: null, desiredMonthlyAmount: null }); }
  return <main className="ui-page max-w-5xl"><header className="max-w-3xl"><p className="ui-eyebrow">SEASON 3 · FINANCIAL JOURNEY</p><h1 className="ui-page-heading mt-2">{text.title}</h1><p className="mt-3 text-base leading-7 text-muted">{text.description}</p></header>
    <ol className="mt-8 grid grid-cols-5 gap-2" aria-label="Financial journey setup">{text.steps.map((label, index) => <li className="min-w-0 text-center" key={label}><span className={cx("mx-auto flex h-9 w-9 items-center justify-center rounded-full border text-xs font-bold", index <= step ? "border-brand bg-brand text-white" : "border-line bg-surface-subtle text-muted")}>{index + 1}</span><span className="mt-2 hidden text-xs font-semibold text-muted sm:block">{label}</span></li>)}</ol>
    <div className="ui-alert-info mt-6">{text.privacy}</div>{mutation.isError ? <div className="ui-alert-danger mt-4">{text.error}</div> : null}
    <form className="ui-card mt-6 p-6 sm:p-8" onSubmit={submit}><p className="text-xs font-bold text-brand">STEP {step + 1} / 5</p><h2 className="mt-2 text-2xl font-bold text-ink">{text.steps[step]}</h2>
      {step === 1 ? <section className="mt-6 grid gap-6 sm:grid-cols-2" data-step="1"><Field label={text.nationality}><select className={ui.input} name="nationality" required value={nationality} onChange={(event) => setNationality(event.target.value)}><option value="" disabled>{text.chooseNationality}</option>{nationalityOptions.map((option) => <option key={option.code} value={option.code}>{option.flag} {option.names[locale]} ({option.code})</option>)}</select></Field><Field label={text.purpose}><select className={ui.input} name="financialPurpose" value={purpose} onChange={(event) => setPurpose(event.target.value as FinancialPurposeCode)}>{allFinancialPurposes.map((value) => <option key={value} value={value}>{financialPurposeLabel(locale, value)}</option>)}</select></Field></section> : null}
      {step === 2 ? <section className="mt-6" data-step="2"><p className="text-sm text-muted">{text.optional}</p><div className="mt-5 grid gap-6 sm:grid-cols-2"><BooleanField label={text.residenceCard} name="hasResidenceCard" locale={locale} /><BooleanField label={text.passport} name="hasPassport" locale={locale} /><BooleanField label={text.phone} name="hasDomesticPhone" locale={locale} /><BooleanField label={text.phoneVerify} name="canDomesticPhoneVerify" locale={locale} /><BooleanField label={text.account} name="hasKoreanBankAccount" locale={locale} /><BooleanField label={text.credit} name="hasKoreanCreditHistory" locale={locale} /><ChoiceRadioGroup label={text.channel} name="preferredChannel" options={[{ label: text.unknown, value: "" }, { label: "Online / Mobile", value: "ONLINE" }, { label: "Branch", value: "BRANCH" }]} /></div></section> : null}
      {mutation.isPending ? <div className="ui-alert-info mt-6">{text.saving}</div> : null}<div className="mt-8 flex justify-between gap-3"><button className="ui-button ui-button-secondary disabled:invisible" disabled={step <= 1 || mutation.isPending} onClick={() => setStep((value) => Math.max(value - 1, 1))} type="button">← {text.back}</button>{step < 2 ? <button aria-label={`profile-step-${step}-next`} className="ui-button ui-button-primary" data-profile-next={step} disabled={!nationality} key={`profile-next-${step}`} onClick={(event) => { event.preventDefault(); setStep(2); }} type="button">{text.next} →</button> : <button className="ui-button ui-button-primary" disabled={mutation.isPending || !nationality} key="profile-submit" type="submit">{text.save} →</button>}</div>
    </form></main>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="ui-label">{label}{children}</label>; }
function BooleanField({ label, name, locale }: { label: string; name: string; locale: Locale }) {
  const text = copy[locale];
  return <ChoiceRadioGroup label={label} name={name} options={[{ label: text.unknown, value: "" }, { label: text.yes, value: "true" }, { label: text.no, value: "false" }]} />;
}

function ChoiceRadioGroup({ label, name, options }: { label: string; name: string; options: Array<{ label: string; value: string }> }) {
  return <fieldset className="min-w-0">
    <legend className="ui-label">{label}</legend>
    <div className="mt-2 grid grid-cols-3 gap-2">
      {options.map((option) => {
        const id = `${name}-${option.value || "unknown"}`;
        return <label className="relative min-w-0 cursor-pointer" htmlFor={id} key={id}>
          <input className="peer sr-only" defaultChecked={option.value === ""} id={id} name={name} type="radio" value={option.value} />
          <span className="flex min-h-12 items-center justify-center rounded-control border border-line-strong bg-surface px-2 py-2 text-center text-xs font-semibold leading-5 text-muted transition duration-200 hover:border-brand hover:bg-brand-soft peer-checked:border-brand peer-checked:bg-brand-soft peer-checked:text-brand peer-focus-visible:ring-4 peer-focus-visible:ring-brand-soft sm:px-3 sm:text-sm">
            {option.label}
          </span>
        </label>;
      })}
    </div>
  </fieldset>;
}
function optionalBoolean(value: FormDataEntryValue | null): boolean | null { return value === "true" ? true : value === "false" ? false : null; }
