"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useRef, useState, type FormEvent, type MouseEvent, type ReactNode } from "react";
import { useLocale } from "@/components/providers/locale-provider";
import { LocalizedDateField } from "@/components/localized-date-field";
import { localeOptions } from "@/i18n/config";
import { amountInWords, digitsOnly, formatGroupedDigits } from "@/lib/amount-words";
import { nationalityOptions } from "@/lib/nationalities";
import { createProfile, getVisas } from "@/services/profile";

const inputClass = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 outline-none transition focus:border-blue-600 focus:ring-4 focus:ring-blue-100";
const wizardCopy = {
  ko: { steps: ["기본정보", "체류정보", "직업·소득", "금융목적", "사전진단"], next: "다음 단계", back: "이전", chooseNationality: "국적을 선택하세요", nationalityReason: "언어와 별도로 실제 국적을 선택합니다. 일부 상품의 공식 국적 조건과 비교할 때 사용합니다.", optionalHint: "선택정보 · 추천 정렬에 활용됩니다", descriptions: ["표시 언어와 별개로 실제 국적과 나이 정보를 확인합니다.", "체류자격과 국내 체류기간을 공개조건과 비교합니다.", "소득·근속 조건이 있는 상품을 확인합니다.", "찾고 있는 금융상품과 선호조건을 알려주세요."], reasons: { birth: "상품의 공개된 연령 조건과 비교할 때 사용합니다.", visa: "공식 자료에 명시된 허용 체류자격과 비교합니다.", expiry: "비자 잔여기간 조건을 계산합니다.", residency: "한국 체류기간 조건을 계산합니다.", occupation: "직업별 조건부 필요서류를 안내합니다.", employment: "고용형태 조건과 필요서류를 확인합니다.", income: "원화 기준 공개 소득조건과 비교합니다.", duration: "근속기간 또는 소득증빙기간 조건을 확인합니다.", purpose: "금융목적이 맞는 상품을 먼저 정렬합니다." } },
  en: { steps: ["Basic information", "Stay information", "Job & income", "Financial purpose", "Pre-check"], next: "Next step", back: "Back", chooseNationality: "Select your nationality", nationalityReason: "Select your actual nationality independently from the display language. It is compared only with published nationality conditions.", optionalHint: "Optional · used only to improve ranking", descriptions: ["Confirm your actual nationality separately from your display language, plus age information.", "Compares your status and period of stay with public conditions.", "Checks products with income or employment-duration conditions.", "Tell us what product and preferences you are looking for."], reasons: { birth: "Used only to compare published age conditions.", visa: "Compared with eligible statuses published by the official source.", expiry: "Used to calculate remaining visa months.", residency: "Used to calculate completed months of residence in Korea.", occupation: "Used to show conditional documents related to your work.", employment: "Used for employment conditions and conditional documents.", income: "Compared with published income conditions in KRW.", duration: "Used for employment or income-evidence duration conditions.", purpose: "Used to rank products matching your financial purpose first." } },
  vi: { steps: ["Thông tin cơ bản", "Thông tin cư trú", "Nghề nghiệp & thu nhập", "Mục đích tài chính", "Kiểm tra sơ bộ"], next: "Bước tiếp theo", back: "Quay lại", chooseNationality: "Chọn quốc tịch của bạn", nationalityReason: "Chọn quốc tịch thực tế độc lập với ngôn ngữ hiển thị. Thông tin này chỉ được so sánh với điều kiện quốc tịch đã công khai.", optionalHint: "Tùy chọn · chỉ dùng để cải thiện thứ tự gợi ý", descriptions: ["Xác nhận quốc tịch thực tế riêng với ngôn ngữ hiển thị và thông tin tuổi.", "So sánh tư cách và thời gian cư trú với điều kiện công khai.", "Kiểm tra sản phẩm có điều kiện thu nhập hoặc thời gian làm việc.", "Cho biết sản phẩm và điều kiện ưu tiên bạn đang tìm."], reasons: { birth: "Chỉ dùng để so sánh điều kiện tuổi đã công khai.", visa: "So sánh với tư cách lưu trú trong nguồn chính thức.", expiry: "Dùng để tính số tháng visa còn lại.", residency: "Dùng để tính thời gian cư trú tại Hàn Quốc.", occupation: "Dùng để hiển thị giấy tờ có điều kiện theo nghề nghiệp.", employment: "Dùng để kiểm tra điều kiện việc làm và giấy tờ.", income: "So sánh với điều kiện thu nhập bằng KRW.", duration: "Dùng để kiểm tra thời gian làm việc hoặc chứng minh thu nhập.", purpose: "Dùng để ưu tiên sản phẩm phù hợp với mục đích tài chính." } },
} as const;

export function ProfileWizard() {
  const { locale, setLocale, text } = useLocale();
  const router = useRouter();
  const profileText = text.profile;
  const wizard = wizardCopy[locale];
  const formRef = useRef<HTMLFormElement>(null);
  const [step, setStep] = useState(0);
  const [hasError, setHasError] = useState(false);
  const [monthlyIncome, setMonthlyIncome] = useState("");
  const [nationality, setNationality] = useState("");
  const visas = useQuery({ queryKey: ["visas"], queryFn: getVisas });

  const mutation = useMutation({ mutationFn: createProfile, onSuccess: (profile) => { setHasError(false); localStorage.setItem("visafyProfileId", String(profile.id)); localStorage.setItem("visafyProfileSessionId", profile.sessionId); router.push("/products"); }, onError: () => { setHasError(true); setStep(3); } });

  function next(event: MouseEvent<HTMLButtonElement>) {
    event.preventDefault();
    const controls = formRef.current?.querySelector<HTMLElement>(`[data-step="${step}"]`)?.querySelectorAll<HTMLInputElement | HTMLSelectElement>("input, select");
    for (const control of Array.from(controls ?? [])) { if (!control.checkValidity()) { control.reportValidity(); return; } }
    setStep((current) => Math.min(3, current + 1));
  }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); setStep(4);
    mutation.mutate({ nationality, birthDate: data.get("birthDate"), visaType: data.get("visaType"), visaExpiry: data.get("visaExpiry"), residencyStartDate: data.get("residencyStartDate"), occupation: data.get("occupation"), employmentType: data.get("employmentType"), monthlyIncome: Number(monthlyIncome), employmentDurationMonths: Number(data.get("employmentDurationMonths")), financialPurpose: data.get("financialPurpose"), language: locale, hasBankAccount: optionalBoolean(data.get("hasBankAccount")), housingType: data.get("housingType") || null, desiredAmount: data.get("desiredAmount") ? Number(data.get("desiredAmount")) : null, preferredBank: data.get("preferredBank") || null, residentStatus: data.get("residentStatus"), hasExistingProductAccount: null, desiredMonthlyAmount: null });
  }

  return <main className="mx-auto max-w-5xl px-5 py-10 sm:px-6 sm:py-14">
    <header className="max-w-3xl"><p className="text-sm font-semibold text-blue-700">{profileText.eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{profileText.title}</h1><p className="mt-3 text-slate-600">{profileText.description}</p></header>
    <nav className="mt-8" aria-label="Profile steps"><ol className="flex items-center">{wizard.steps.map((label, index) => <li className="flex min-w-0 flex-1 items-center" key={label}><div className="flex min-w-0 items-center gap-2"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-black ${index < step ? "bg-emerald-600 text-white" : index === step ? "bg-blue-700 text-white ring-4 ring-blue-100" : "bg-slate-200 text-slate-500"}`}>{index < step ? "✓" : index + 1}</span><span className={`hidden whitespace-nowrap text-xs font-bold sm:inline ${index === step ? "text-blue-800" : "text-slate-500"}`}>{label}</span></div>{index < 4 ? <span className={`mx-1 h-px flex-1 sm:mx-3 ${index < step ? "bg-emerald-400" : "bg-slate-200"}`} /> : null}</li>)}</ol><p className="mt-3 text-sm font-bold text-blue-800 sm:hidden">{wizard.steps[step]}</p></nav>
    <div className="mt-7 flex flex-wrap gap-2">{localeOptions.map((option) => <button className={`rounded-full border px-4 py-2 text-sm font-semibold ${locale === option.locale ? "border-blue-700 bg-blue-50 text-blue-800" : "border-slate-300 bg-white"}`} key={option.locale} onClick={() => setLocale(option.locale)} type="button"><span aria-hidden>{option.flag}</span> {option.language}</button>)}</div>
    <div className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-950">{profileText.privacy}</div>{hasError ? <div className="mt-4 rounded-xl bg-rose-100 p-4 text-rose-800">{profileText.saveError}</div> : null}
    <form className="mt-7 rounded-3xl border bg-white p-6 shadow-sm sm:p-9" onSubmit={submit} ref={formRef}>
      <div className="mb-7"><p className="text-xs font-black uppercase tracking-widest text-blue-700">STEP {Math.min(step + 1, 5)} / 5</p><h2 className="mt-2 text-2xl font-bold">{wizard.steps[step]}</h2>{step < 4 ? <p className="mt-2 text-sm text-slate-500">{wizard.descriptions[step]}</p> : null}</div>
      <section className={step === 0 ? "grid gap-5 sm:grid-cols-2" : "hidden"} data-step="0"><Field label={profileText.nationality} reason={wizard.nationalityReason}><select className={inputClass} name="nationality" required value={nationality} onChange={(event) => setNationality(event.target.value)}><option value="" disabled>{wizard.chooseNationality}</option>{nationalityOptions.map((option) => <option key={option.code} value={option.code}>{option.flag} {option.names[locale]} ({option.code})</option>)}</select></Field><LocalizedDateField label={profileText.birthDate} name="birthDate" minYear={new Date().getFullYear() - 100} maxYear={new Date().getFullYear()} hint={profileText.dateInputHint} invalidMessage={profileText.invalidDate} reason={wizard.reasons.birth} /></section>
      <section className={step === 1 ? "grid gap-5 sm:grid-cols-2" : "hidden"} data-step="1"><Field label={profileText.visaType} reason={wizard.reasons.visa}><select className={inputClass} name="visaType" required defaultValue=""><option value="" disabled>{profileText.chooseVisa}</option>{visas.data?.map((visa) => <option key={visa.visaCode} value={visa.visaCode}>{visa.visaCode} · {profileText.visaNames[visa.visaCode as keyof typeof profileText.visaNames]}</option>)}</select></Field><Field label={profileText.residentStatus}><select className={inputClass} name="residentStatus" required defaultValue=""><option value="" disabled>—</option><option value="RESIDENT">{profileText.resident}</option><option value="NON_RESIDENT">{profileText.nonResident}</option></select></Field><LocalizedDateField label={profileText.visaExpiry} name="visaExpiry" minYear={new Date().getFullYear()} maxYear={new Date().getFullYear() + 20} hint={profileText.dateInputHint} invalidMessage={profileText.invalidDate} reason={wizard.reasons.expiry} /><LocalizedDateField label={profileText.residencyStartDate} name="residencyStartDate" minYear={new Date().getFullYear() - 60} maxYear={new Date().getFullYear()} hint={profileText.dateInputHint} invalidMessage={profileText.invalidDate} reason={wizard.reasons.residency} /></section>
      <section className={step === 2 ? "grid gap-5 sm:grid-cols-2" : "hidden"} data-step="2"><Field label={profileText.occupation} reason={wizard.reasons.occupation}><input className={inputClass} name="occupation" placeholder={profileText.occupationExample} required /></Field><Field label={profileText.employmentType} reason={wizard.reasons.employment}><select className={inputClass} name="employmentType"><option value="REGULAR">{profileText.employment.regular}</option><option value="CONTRACT">{profileText.employment.contract}</option><option value="PART_TIME">{profileText.employment.partTime}</option><option value="SELF_EMPLOYED">{profileText.employment.selfEmployed}</option><option value="STUDENT">{profileText.employment.student}</option></select></Field><Field label={profileText.monthlyIncome} reason={wizard.reasons.income}><input aria-describedby="monthly-income-words" className={inputClass} inputMode="numeric" onChange={(event) => setMonthlyIncome(digitsOnly(event.target.value))} placeholder="3,000,000" required type="text" value={formatGroupedDigits(monthlyIncome, locale)} /><span className="mt-2 block min-h-5 text-xs font-bold text-blue-700" id="monthly-income-words">{monthlyIncome ? `${profileText.monthlyIncomeWords}: ${amountInWords(monthlyIncome, locale)}` : ""}</span></Field><Field label={profileText.employmentDuration} reason={wizard.reasons.duration}><input className={inputClass} min="0" name="employmentDurationMonths" type="number" required /></Field></section>
      <section className={step === 3 ? "space-y-7" : "hidden"} data-step="3"><Field label={profileText.financialPurpose} reason={wizard.reasons.purpose}><select className={inputClass} name="financialPurpose"><option value="ACCOUNT">{profileText.purpose.account}</option><option value="SAVINGS">{profileText.purpose.savings}</option><option value="LOAN">{profileText.purpose.loan}</option><option value="CARD">{profileText.purpose.card}</option><option value="INVESTMENT">{profileText.purpose.investment}</option></select></Field><details className="rounded-2xl border p-5"><summary className="cursor-pointer font-bold">{profileText.optional} <span className="ml-2 text-xs font-medium text-slate-400">{wizard.optionalHint}</span></summary><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label={profileText.hasBankAccount}><select className={inputClass} defaultValue="" name="hasBankAccount"><option value="">—</option><option value="true">{profileText.yes}</option><option value="false">{profileText.no}</option></select></Field><Field label={profileText.housingType}><input className={inputClass} name="housingType" placeholder={profileText.housingExample} /></Field><Field label={profileText.desiredAmount}><input className={inputClass} min="0" name="desiredAmount" type="number" /></Field><Field label={profileText.preferredBank}><input className={inputClass} name="preferredBank" /></Field></div></details></section>
      {step === 4 ? <section className="rounded-2xl bg-slate-950 p-7 text-white" aria-live="polite"><p className="text-sm font-bold text-teal-300">{profileText.submitting}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/3 animate-pulse rounded-full bg-teal-400" /></div><p className="mt-4 text-sm text-slate-300">{wizard.steps.slice(0, 4).join(" ✓ · ")} ✓</p></section> : null}
      {step < 4 ? <div className="mt-9 flex items-center justify-between gap-3"><button className="rounded-xl border px-5 py-3 font-bold text-slate-600 disabled:invisible" disabled={step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))} type="button">← {wizard.back}</button>{step < 3 ? <button className="rounded-xl bg-blue-700 px-6 py-3 font-bold text-white" onClick={next} type="button">{wizard.next} →</button> : <button className="rounded-xl bg-blue-700 px-6 py-3 font-bold text-white disabled:opacity-50" disabled={mutation.isPending || visas.isLoading} type="submit">{profileText.submit} →</button>}</div> : null}
    </form>
  </main>;
}

function Field({ label, reason, children }: { label: string; reason?: string; children: ReactNode }) { return <label className="text-sm font-medium"><span className="inline-flex items-center gap-1.5">{label}{reason ? <span aria-label={reason} className="inline-flex h-5 w-5 cursor-help items-center justify-center rounded-full bg-slate-100 text-[11px] font-bold text-slate-500" title={reason}>?</span> : null}</span>{children}</label>; }

function optionalBoolean(value: FormDataEntryValue | null): boolean | null {
  if (value === "true") return true;
  if (value === "false") return false;
  return null;
}
