package com.visafy.eligibility;

public enum InsufficientReasonCode {
    SOURCE_INSUFFICIENT,
    SOURCE_CONFLICT,
    RULE_REVIEW_INCOMPLETE,
    MISSING_REQUIRED_PROFILE_FIELD,
    UNSUPPORTED_RULE_KEY,
    INVALID_RULE_VALUE,
    EXPIRED_RULE
}
