CREATE TABLE source_document (
    id BIGINT NOT NULL AUTO_INCREMENT,
    institution VARCHAR(120) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    title VARCHAR(255) NOT NULL,
    source_url VARCHAR(1000) NOT NULL,
    snapshot_text LONGTEXT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    retrieved_at DATETIME(6) NOT NULL,
    valid_from DATE NULL,
    valid_to DATE NULL,
    review_status VARCHAR(40) NOT NULL,
    last_verified_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_content_hash (content_hash),
    INDEX idx_source_review_status (review_status),
    INDEX idx_source_valid_to (valid_to)
);

CREATE TABLE rule_candidate (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_document_id BIGINT NOT NULL,
    product_code VARCHAR(120) NOT NULL,
    rule_key VARCHAR(120) NOT NULL,
    operator VARCHAR(40) NOT NULL,
    rule_value TEXT NOT NULL,
    rule_level VARCHAR(40) NOT NULL,
    source_excerpt TEXT NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    review_status VARCHAR(40) NOT NULL,
    last_verified_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_rule_candidate_source FOREIGN KEY (source_document_id) REFERENCES source_document (id),
    INDEX idx_rule_candidate_lookup (product_code, rule_key, review_status)
);

CREATE TABLE temp_profile (
    id BIGINT NOT NULL AUTO_INCREMENT,
    session_id CHAR(36) NOT NULL,
    nationality VARCHAR(80) NOT NULL,
    birth_date DATE NOT NULL,
    visa_type VARCHAR(10) NOT NULL,
    visa_expiry DATE NOT NULL,
    residency_start_date DATE NOT NULL,
    occupation VARCHAR(120) NOT NULL,
    employment_type VARCHAR(80) NOT NULL,
    monthly_income DECIMAL(15,2) NOT NULL,
    employment_duration_months INT NOT NULL,
    financial_purpose VARCHAR(120) NOT NULL,
    language VARCHAR(10) NOT NULL,
    has_bank_account BOOLEAN NULL,
    housing_type VARCHAR(80) NULL,
    desired_amount DECIMAL(15,2) NULL,
    preferred_bank VARCHAR(120) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_temp_profile_session (session_id),
    INDEX idx_temp_profile_expires_at (expires_at)
);
