CREATE TABLE financial_product (
    id BIGINT NOT NULL AUTO_INCREMENT,
    product_code VARCHAR(120) NOT NULL,
    institution VARCHAR(120) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_type VARCHAR(40) NOT NULL,
    financial_purpose VARCHAR(40) NOT NULL,
    description TEXT NOT NULL,
    target_summary TEXT NOT NULL,
    source_document_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    foreigner_target BOOLEAN NOT NULL,
    information_base_date DATE NOT NULL,
    public_conditions TEXT NOT NULL,
    additional_conditions TEXT NOT NULL,
    required_documents TEXT NOT NULL,
    application_method TEXT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_financial_product_code (product_code),
    CONSTRAINT fk_financial_product_source FOREIGN KEY (source_document_id) REFERENCES source_document (id),
    INDEX idx_financial_product_filter (active, financial_purpose, product_type, institution),
    INDEX idx_financial_product_foreigner (foreigner_target)
);

CREATE TABLE product_rule (
    id BIGINT NOT NULL AUTO_INCREMENT,
    rule_candidate_id BIGINT NOT NULL,
    source_document_id BIGINT NOT NULL,
    product_code VARCHAR(120) NOT NULL,
    rule_key VARCHAR(120) NOT NULL,
    operator VARCHAR(40) NOT NULL,
    rule_value TEXT NOT NULL,
    rule_level VARCHAR(40) NOT NULL,
    source_excerpt TEXT NOT NULL,
    active BOOLEAN NOT NULL,
    last_verified_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_product_rule_candidate (rule_candidate_id),
    CONSTRAINT fk_product_rule_candidate FOREIGN KEY (rule_candidate_id) REFERENCES rule_candidate (id),
    CONSTRAINT fk_product_rule_source FOREIGN KEY (source_document_id) REFERENCES source_document (id),
    INDEX idx_product_rule_runtime (product_code, active, rule_key)
);
