package com.visafy.product;

public enum ProductCategory {
    DEMAND_DEPOSIT, SAVINGS, TIME_DEPOSIT, DEBIT_CARD, CREDIT_CARD,
    PERSONAL_LOAN, HOUSING_LOAN, REMITTANCE, SECURITIES, POLICY_FINANCE
}
