import type { Locale } from "@/i18n/config";

/**
 * Display translations for the long-form product fields stored in Korean.
 *
 * Same contract as `product-localization.ts`: a product without an entry keeps the stored
 * Korean text, so a newly registered product renders exactly as it does today.
 */

type FieldTranslations = Partial<Record<Locale, string>>;

export type ProductDetailField =
  | "description"
  | "publicConditions"
  | "additionalConditions"
  | "requiredDocuments"
  | "applicationMethod"
  | "sourceTitle";

const details: Record<string, Partial<Record<ProductDetailField, FieldTranslations>>> = {
  "KB-MY-SAVINGS": {
    description: { en: "A flexible savings plan you build by combining conditions", vi: "Sổ tiết kiệm linh hoạt bạn tự tạo bằng cách kết hợp các điều kiện", zh: "通过组合条件自行设定的自由存入式零存整取", ja: "条件を組み合わせて作る自由積立式の積立預金", th: "บัญชีออมทรัพย์แบบยืดหยุ่นที่คุณกำหนดเงื่อนไขเอง" },
    publicConditions: { en: "KRW 10,000 to 1,000,000 per month", vi: "Từ 10.000 đến 1.000.000 KRW mỗi tháng", zh: "每月 1 万至 100 万韩元", ja: "毎月1万ウォン以上100万ウォン以下", th: "เดือนละ 10,000 ถึง 1,000,000 วอน" },
    additionalConditions: { en: "Whether foreign customers can open this through KB Star Banking must be confirmed", vi: "Cần xác nhận người nước ngoài có thể mở qua KB Star Banking hay không", zh: "需确认外国人是否可通过 KB 星银行新开户", ja: "外国人がKBスターバンキングで新規開設できるかは確認が必要です", th: "ต้องยืนยันว่าชาวต่างชาติเปิดผ่าน KB Star Banking ได้หรือไม่" },
    requiredDocuments: { en: "An official identity document for foreign customers, plus any additional documents the bank requests", vi: "Giấy tờ xác minh danh tính chính thức dành cho người nước ngoài và giấy tờ bổ sung ngân hàng yêu cầu", zh: "外国人实名确认证件及银行要求的补充材料", ja: "外国人の実名確認書類、および銀行が求める追加書類", th: "เอกสารยืนยันตัวตนอย่างเป็นทางการสำหรับชาวต่างชาติ และเอกสารเพิ่มเติมที่ธนาคารร้องขอ" },
    applicationMethod: { en: "KB Star Banking or a branch", vi: "KB Star Banking hoặc chi nhánh", zh: "KB 星银行或营业网点", ja: "KBスターバンキングまたは店舗", th: "KB Star Banking หรือที่สาขา" },
    sourceTitle: { en: "KB My Own Savings official product page", vi: "Trang sản phẩm chính thức KB My Own Savings", zh: "KB我的专属零存整取官方产品页", ja: "KB マイ積立預金 公式商品ページ", th: "หน้าผลิตภัณฑ์อย่างเป็นทางการของ KB My Own Savings" },
  },
  "KB-STAR-TIME-DEPOSIT": {
    description: { en: "A digital time deposit opened through internet banking or KB Star Banking", vi: "Tiền gửi kỳ hạn kỹ thuật số mở qua internet banking hoặc KB Star Banking", zh: "通过网上银行与 KB 星银行开立的数字定期存款", ja: "インターネットバンキングとKBスターバンキングで加入するデジタル定期預金", th: "เงินฝากประจำแบบดิจิทัลที่เปิดผ่านอินเทอร์เน็ตแบงก์กิ้งหรือ KB Star Banking" },
    publicConditions: { en: "Deposit of KRW 1,000,000 or more", vi: "Số tiền gửi từ 1.000.000 KRW trở lên", zh: "存入金额 100 万韩元以上", ja: "預入金額100万ウォン以上", th: "ยอดฝากตั้งแต่ 1,000,000 วอนขึ้นไป" },
    additionalConditions: { en: "Whether foreign customers can open this online must be confirmed", vi: "Cần xác nhận người nước ngoài có thể mở trực tuyến hay không", zh: "需确认外国人是否可线上新开户", ja: "外国人がオンラインで新規開設できるかは確認が必要です", th: "ต้องยืนยันว่าชาวต่างชาติเปิดบัญชีออนไลน์ได้หรือไม่" },
    requiredDocuments: { en: "An official identity document for foreign customers, plus any additional documents the bank requests", vi: "Giấy tờ xác minh danh tính chính thức dành cho người nước ngoài và giấy tờ bổ sung ngân hàng yêu cầu", zh: "外国人实名确认证件及银行要求的补充材料", ja: "外国人の実名確認書類、および銀行が求める追加書類", th: "เอกสารยืนยันตัวตนอย่างเป็นทางการสำหรับชาวต่างชาติ และเอกสารเพิ่มเติมที่ธนาคารร้องขอ" },
    applicationMethod: { en: "Internet banking or KB Star Banking", vi: "Internet banking hoặc KB Star Banking", zh: "网上银行或 KB 星银行", ja: "インターネットバンキングまたはKBスターバンキング", th: "อินเทอร์เน็ตแบงก์กิ้งหรือ KB Star Banking" },
    sourceTitle: { en: "KB Star Time Deposit official product page", vi: "Trang sản phẩm chính thức KB Star Time Deposit", zh: "KB Star 定期存款官方产品页", ja: "KB Star 定期預金 公式商品ページ", th: "หน้าผลิตภัณฑ์อย่างเป็นทางการของ KB Star Time Deposit" },
  },
  "KB-LIVELIHOOD-ACCOUNT": {
    description: { en: "A seizure-protected account that shields up to KRW 2,500,000 of living expenses", vi: "Tài khoản chống kê biên bảo vệ tối đa 2.500.000 KRW chi phí sinh hoạt", zh: "最高保护 250 万韩元生活资金的防查封存折", ja: "最大250万ウォンまで生活資金を保護する差押防止通帳", th: "บัญชีคุ้มครองการอายัด ปกป้องค่าครองชีพสูงสุด 2,500,000 วอน" },
    publicConditions: { en: "One account per person across all financial institutions", vi: "Mỗi người một tài khoản trên toàn bộ tổ chức tài chính", zh: "全金融机构 1 人 1 账户", ja: "全金融機関を通じて1人1口座", th: "1 คน 1 บัญชี ในทุกสถาบันการเงิน" },
    additionalConditions: { en: "For mobile opening, whether identity verification actually works must be confirmed", vi: "Khi mở qua di động, cần xác nhận việc xác minh danh tính có thực hiện được không", zh: "通过手机新开户时，需额外确认能否完成本人确认", ja: "モバイルで新規開設する場合、本人確認が実際に可能かの追加確認が必要です", th: "หากเปิดผ่านมือถือ ต้องยืนยันเพิ่มเติมว่าทำการยืนยันตัวตนได้จริงหรือไม่" },
    requiredDocuments: { en: "A residence card, domestic residence report card, or permanent residence card, whichever applies", vi: "Thẻ cư trú, giấy khai báo cư trú trong nước hoặc thẻ thường trú, tùy trường hợp", zh: "外国人登录证、国内居所申报证或永驻证中适用的证件", ja: "外国人登録証・国内居所申告証・永住証のうち該当する証明書", th: "บัตรประจำตัวคนต่างด้าว บัตรแจ้งถิ่นที่อยู่ในประเทศ หรือบัตรผู้มีถิ่นที่อยู่ถาวร ตามแต่กรณี" },
    applicationMethod: { en: "A branch or KB Star Banking", vi: "Chi nhánh hoặc KB Star Banking", zh: "网点或 KB 星银行", ja: "支店またはKBスターバンキング", th: "ที่สาขาหรือ KB Star Banking" },
    sourceTitle: { en: "Launch notice for the new KB Livelihood Account", vi: "Thông báo ra mắt sản phẩm mới KB Livelihood Account", zh: "新产品 KB生计费账户 上市公告", ja: "新商品 KB生活費口座 発売のお知らせ", th: "ประกาศเปิดตัวผลิตภัณฑ์ใหม่ KB Livelihood Account" },
  },
  "SHINHAN-LIVELIHOOD-ACCOUNT": {
    description: { en: "A seizure-protected savings deposit that shields monthly living expenses", vi: "Tiền gửi tiết kiệm chống kê biên bảo vệ chi phí sinh hoạt hàng tháng", zh: "保护每月生活维持资金的防查封储蓄存款", ja: "毎月の生計維持資金を保護する差押防止貯蓄預金", th: "เงินฝากออมทรัพย์คุ้มครองการอายัดเพื่อปกป้องค่าครองชีพรายเดือน" },
    publicConditions: { en: "One account per person across all financial institutions", vi: "Mỗi người một tài khoản trên toàn bộ tổ chức tài chính", zh: "全金融机构 1 人 1 账户", ja: "全金融機関を通じて1人1口座", th: "1 คน 1 บัญชี ในทุกสถาบันการเงิน" },
    additionalConditions: { en: "Whether foreign customers can open this on mobile must be confirmed with the bank", vi: "Cần xác nhận với ngân hàng việc người nước ngoài mở qua di động", zh: "外国人能否通过手机新开户需向银行确认", ja: "外国人がモバイルで新規開設できるかは銀行の確認が必要です", th: "ต้องยืนยันกับธนาคารว่าชาวต่างชาติเปิดผ่านมือถือได้หรือไม่" },
    requiredDocuments: { en: "A residence card, domestic residence report card, or permanent residence card, whichever applies", vi: "Thẻ cư trú, giấy khai báo cư trú trong nước hoặc thẻ thường trú, tùy trường hợp", zh: "外国人登录证、国内居所申报证或永驻证中适用的证件", ja: "外国人登録証・国内居所申告証・永住証のうち該当する証明書", th: "บัตรประจำตัวคนต่างด้าว บัตรแจ้งถิ่นที่อยู่ในประเทศ หรือบัตรผู้มีถิ่นที่อยู่ถาวร ตามแต่กรณี" },
    applicationMethod: { en: "A branch or Shinhan SOL Bank (foreign-customer mobile availability confirmed separately)", vi: "Chi nhánh hoặc Shinhan SOL Bank (khả năng dùng di động cho người nước ngoài xác nhận riêng)", zh: "网点或新韩 SOL 银行（外国人手机可用性需另行确认）", ja: "店舗または新韓SOLバンク（外国人のモバイル可否は別途確認）", th: "ที่สาขาหรือ Shinhan SOL Bank (ยืนยันการใช้มือถือสำหรับชาวต่างชาติแยกต่างหาก)" },
    sourceTitle: { en: "Shinhan Bank official deposit product guide - Shinhan Livelihood Account", vi: "Hướng dẫn sản phẩm tiền gửi chính thức Shinhan - Shinhan Livelihood Account", zh: "新韩银行存款产品官方指引 - 新韩生计费账户", ja: "新韓銀行 預金商品 公式案内 - 新韓 生活費口座", th: "คู่มือผลิตภัณฑ์เงินฝากอย่างเป็นทางการของธนาคารชินฮัน - Shinhan Livelihood Account" },
  },
  "HANA-SALARY-COMPOUND-SAVINGS": {
    description: { en: "A monthly compound savings plan with a preferential rate for salary transfers", vi: "Tiết kiệm lãi kép hàng tháng với lãi suất ưu đãi cho khách nhận lương", zh: "对薪资实绩提供优惠利率的月复利零存整取", ja: "給与実績に優遇金利を提供する月複利の積立預金", th: "บัญชีออมทรัพย์ดอกเบี้ยทบต้นรายเดือน พร้อมอัตราพิเศษสำหรับผู้รับเงินเดือน" },
    publicConditions: { en: "One account per person, KRW 10,000 to 3,000,000", vi: "Mỗi người một tài khoản, từ 10.000 đến 3.000.000 KRW", zh: "1 人 1 账户，1 万至 300 万韩元", ja: "1人1口座、1万ウォン以上300万ウォン以下", th: "1 คน 1 บัญชี ตั้งแต่ 10,000 ถึง 3,000,000 วอน" },
    additionalConditions: { en: "Whether foreign customers can open this through internet or mobile banking must be confirmed", vi: "Cần xác nhận người nước ngoài có thể mở qua internet hoặc mobile banking hay không", zh: "需确认外国人是否可通过网上银行或手机银行新开户", ja: "外国人がインターネット・スマホバンキングで新規開設できるかは確認が必要です", th: "ต้องยืนยันว่าชาวต่างชาติเปิดผ่านอินเทอร์เน็ตหรือโมบายแบงก์กิ้งได้หรือไม่" },
    requiredDocuments: { en: "An official identity document such as a passport or residence card", vi: "Giấy tờ xác minh danh tính chính thức như hộ chiếu hoặc thẻ cư trú", zh: "护照或外国人登录证等官方实名确认证件", ja: "パスポートまたは外国人登録証などの公式な実名確認書類", th: "เอกสารยืนยันตัวตนอย่างเป็นทางการ เช่น หนังสือเดินทางหรือบัตรประจำตัวคนต่างด้าว" },
    applicationMethod: { en: "A branch, internet banking, or mobile banking", vi: "Chi nhánh, internet banking hoặc mobile banking", zh: "营业网点、网上银行或手机银行", ja: "店舗・インターネットバンキング・スマホバンキング", th: "ที่สาขา อินเทอร์เน็ตแบงก์กิ้ง หรือโมบายแบงก์กิ้ง" },
    sourceTitle: { en: "Salary Hana Monthly Compound Savings official product page", vi: "Trang sản phẩm chính thức Salary Hana Monthly Compound Savings", zh: "薪资韩亚月复利零存整取官方产品页", ja: "給与ハナ 月複利積立預金 公式商品ページ", th: "หน้าผลิตภัณฑ์อย่างเป็นทางการของ Salary Hana Monthly Compound Savings" },
  },
  "HANA-EASY-SAVINGS-2025": {
    description: { en: "A savings plan for foreign residents, with eligibility, the one-account rule, and the monthly limit confirmed from the official product page and terms", vi: "Sổ tiết kiệm dành cho người nước ngoài, với đối tượng, quy định một tài khoản và hạn mức hàng tháng xác nhận từ trang sản phẩm và điều khoản chính thức", zh: "面向外国人的零存整取，加入对象、1 人 1 账户及每月存入限额均依据官方产品页与特约确认", ja: "公式商品ページと特約で加入対象・1人1口座・毎月の積立限度を確認した外国人専用の積立預金", th: "บัญชีออมทรัพย์สำหรับชาวต่างชาติ โดยยืนยันคุณสมบัติ กฎ 1 คน 1 บัญชี และวงเงินรายเดือนจากหน้าผลิตภัณฑ์และข้อกำหนดอย่างเป็นทางการ" },
    publicConditions: { en: "Real-name foreign residents, non-residents excluded, one account per person, KRW 10,000 to 300,000 per month", vi: "Người nước ngoài cư trú có danh tính thật, loại trừ người không cư trú, mỗi người một tài khoản, từ 10.000 đến 300.000 KRW mỗi tháng", zh: "实名外国人，排除非居住者，1 人 1 账户，每月 1 万至 30 万韩元", ja: "実名の外国人、非居住者を除く、1人1口座、毎月1万ウォン以上30万ウォン以下", th: "ชาวต่างชาติที่ยืนยันตัวตนจริง ไม่รวมผู้ไม่มีถิ่นที่อยู่ 1 คน 1 บัญชี เดือนละ 10,000 ถึง 300,000 วอน" },
    additionalConditions: { en: "Identity verification and the actual opening are handled by Hana Bank and need its confirmation", vi: "Việc xác minh danh tính và mở tài khoản thực tế do Ngân hàng Hana xử lý và cần xác nhận của ngân hàng", zh: "实名确认与实际开户处理需韩亚银行确认", ja: "実名確認と実際の加入手続きはハナ銀行の確認が必要です", th: "การยืนยันตัวตนและการเปิดบัญชีจริงต้องได้รับการยืนยันจากธนาคารฮานา" },
    requiredDocuments: { en: "The official sources do not publish a separate document list", vi: "Các nguồn chính thức không công bố danh sách giấy tờ riêng", zh: "官方来源未公开单独的提交材料清单", ja: "公式ソースに別途の提出書類一覧は確認できませんでした", th: "แหล่งข้อมูลอย่างเป็นทางการไม่ได้เปิดเผยรายการเอกสารแยกต่างหาก" },
    applicationMethod: { en: "A Hana Bank branch or the official smartphone channel", vi: "Chi nhánh Ngân hàng Hana hoặc kênh điện thoại chính thức", zh: "韩亚银行营业网点或官方手机渠道", ja: "ハナ銀行の店舗または公式スマートフォンチャネル", th: "สาขาธนาคารฮานาหรือช่องทางสมาร์ตโฟนอย่างเป็นทางการ" },
    sourceTitle: { en: "Hana The Easy Savings official product page", vi: "Trang sản phẩm chính thức Hana The Easy Savings", zh: "韩亚更轻松零存整取官方产品页", ja: "ハナ・ジ・イージー積立預金 公式商品ページ", th: "หน้าผลิตภัณฑ์อย่างเป็นทางการของ Hana The Easy Savings" },
  },
  "HANA-EASY-ONE-ACCOUNT": {
    description: { en: "A checking account for foreign customers, with eligibility confirmed from the official product page and the 2025 revised terms", vi: "Tài khoản thanh toán dành cho khách hàng nước ngoài, đối tượng xác nhận từ trang sản phẩm chính thức và điều khoản sửa đổi 2025", zh: "面向外国人的活期存折，加入对象依据官方产品页与 2025 年修订特约确认", ja: "公式商品ページと2025年改定特約で加入対象を確認した外国人専用の普通預金通帳", th: "บัญชีเงินฝากกระแสรายวันสำหรับชาวต่างชาติ ยืนยันคุณสมบัติจากหน้าผลิตภัณฑ์และข้อกำหนดฉบับแก้ไขปี 2025" },
    publicConditions: { en: "Real-name foreign individuals or foreign sole proprietors", vi: "Cá nhân người nước ngoài hoặc hộ kinh doanh người nước ngoài có danh tính thật", zh: "实名外国个人或外国个体经营者", ja: "実名の外国人個人または外国人個人事業者", th: "บุคคลต่างชาติหรือผู้ประกอบการรายย่อยต่างชาติที่ยืนยันตัวตนจริง" },
    additionalConditions: { en: "Identity verification and any fee benefits need Hana Bank confirmation", vi: "Xác minh danh tính và ưu đãi phí cần Ngân hàng Hana xác nhận", zh: "实名确认与手续费优惠条件的适用需韩亚银行确认", ja: "実名確認と手数料優遇条件の適用はハナ銀行の確認が必要です", th: "การยืนยันตัวตนและสิทธิประโยชน์ค่าธรรมเนียมต้องได้รับการยืนยันจากธนาคารฮานา" },
    requiredDocuments: { en: "The official sources do not publish a separate document list, so a branch must confirm it", vi: "Nguồn chính thức không công bố danh sách giấy tờ riêng nên cần chi nhánh xác nhận", zh: "官方来源未公开单独的提交材料清单，需向网点确认", ja: "公式ソースに別途の提出書類一覧が公開されていないため、店舗での確認が必要です", th: "แหล่งข้อมูลอย่างเป็นทางการไม่ได้เปิดเผยรายการเอกสาร จึงต้องยืนยันที่สาขา" },
    applicationMethod: { en: "Apply after consulting at a Hana Bank branch", vi: "Đăng ký sau khi tư vấn tại chi nhánh Ngân hàng Hana", zh: "在韩亚银行营业网点咨询后申请", ja: "ハナ銀行の店舗で相談のうえ申し込み", th: "สมัครหลังปรึกษาที่สาขาธนาคารฮานา" },
    sourceTitle: { en: "Easy-One Pack Account official product page", vi: "Trang sản phẩm chính thức Easy-One Pack Account", zh: "Easy-One Pack 存折官方产品页", ja: "Easy-One Pack 通帳 公式商品ページ", th: "หน้าผลิตภัณฑ์อย่างเป็นทางการของ Easy-One Pack Account" },
  },
  "HANA-EZ-LOAN": {
    description: { en: "A credit loan for foreign workers that compares the visa status, residency period, and salary-income period from the official page, and keeps bank-confirmed conditions separate", vi: "Khoản vay tín chấp cho người lao động nước ngoài, so sánh tư cách lưu trú, thời gian cư trú và thời gian thu nhập lương từ trang chính thức, tách riêng các điều kiện cần ngân hàng xác nhận", zh: "面向外籍劳动者的信用贷款，依据官方详情页比较停留资格、在韩居留期间与薪资收入期间，并分离需银行确认的条件", ja: "公式詳細ページの在留資格・国内居住期間・給与所得期間を比較し、銀行確認条件を分離した外国人労働者向け信用ローン", th: "สินเชื่อส่วนบุคคลสำหรับแรงงานต่างชาติ เปรียบเทียบสถานะวีซ่า ระยะเวลาพำนัก และระยะเวลารายได้เงินเดือนจากหน้าอย่างเป็นทางการ โดยแยกเงื่อนไขที่ธนาคารต้องยืนยัน" },
    publicConditions: { en: "E-7 or E-9 visa, at least 3 months of residency in Korea, at least 3 months of salary income at the current job", vi: "Visa E-7 hoặc E-9, cư trú tại Hàn Quốc từ 3 tháng trở lên, thu nhập lương tại công việc hiện tại từ 3 tháng trở lên", zh: "E-7 或 E-9 停留资格，在韩居留 3 个月以上，现职薪资收入 3 个月以上", ja: "E-7またはE-9、国内居住期間3か月以上、現在の勤務先での給与所得3か月以上", th: "วีซ่า E-7 หรือ E-9 พำนักในเกาหลีอย่างน้อย 3 เดือน และมีรายได้เงินเดือนจากงานปัจจุบันอย่างน้อย 3 เดือน" },
    additionalConditions: { en: "Registration of Hana Bank as the designated foreign-exchange bank, and whether an E-9 holder is a first-time entrant, need bank confirmation", vi: "Việc đăng ký Ngân hàng Hana làm ngân hàng ngoại hối chỉ định và việc người giữ visa E-9 có phải nhập cảnh lần đầu hay không cần ngân hàng xác nhận", zh: "将韩亚银行登记为外汇指定银行，以及 E-9 是否为首次入境，均需银行确认", ja: "ハナ銀行を外国為替指定銀行として登録しているか、E-9が初回入国者かは銀行の確認が必要です", th: "การลงทะเบียนธนาคารฮานาเป็นธนาคารแลกเปลี่ยนเงินตราที่กำหนด และการที่ผู้ถือวีซ่า E-9 เข้าประเทศครั้งแรกหรือไม่ ต้องได้รับการยืนยันจากธนาคาร" },
    requiredDocuments: { en: "Residence card, passport, employment permit or standard labour contract, health insurance enrolment certificate, and proof of employment and annual income", vi: "Thẻ cư trú, hộ chiếu, giấy phép lao động hoặc hợp đồng lao động chuẩn, giấy xác nhận bảo hiểm y tế, và giấy tờ chứng minh việc làm cùng thu nhập năm", zh: "外国人登录证、护照、雇佣许可书或标准劳动合同、健康保险得失确认书、在职及年收入证明材料", ja: "外国人登録証、パスポート、雇用許可書または標準労働契約書、健康保険得喪確認書、在職および年収の証明書類", th: "บัตรประจำตัวคนต่างด้าว หนังสือเดินทาง ใบอนุญาตจ้างงานหรือสัญญาจ้างมาตรฐาน หนังสือรับรองประกันสุขภาพ และหลักฐานการทำงานและรายได้ต่อปี" },
    applicationMethod: { en: "Consultation and application at a Hana Bank branch", vi: "Tư vấn và đăng ký tại chi nhánh Ngân hàng Hana", zh: "在韩亚银行营业网点咨询并申请", ja: "ハナ銀行の店舗での相談および申し込み", th: "ปรึกษาและสมัครที่สาขาธนาคารฮานา" },
    sourceTitle: { en: "Hana Foreigner EZ Loan official detail page", vi: "Trang chi tiết chính thức Hana Foreigner EZ Loan", zh: "韩亚外国人 EZ Loan 官方详情页", ja: "ハナ外国人 EZ Loan 公式詳細ページ", th: "หน้ารายละเอียดอย่างเป็นทางการของ Hana Foreigner EZ Loan" },
  },
  "SHINHAN-SOL-GLOBAL-SAVINGS-2025": {
    description: { en: "A flexible savings plan for foreign residents, with eligibility and the monthly limit confirmed from the official product manual", vi: "Sổ tiết kiệm linh hoạt cho người nước ngoài, đối tượng và hạn mức hàng tháng xác nhận từ bản mô tả sản phẩm chính thức", zh: "面向外国人的自由存入式零存整取，加入对象与每月存入限额依据官方产品说明书确认", ja: "公式商品説明書で加入対象と毎月の積立限度を確認した外国人専用の自由積立式積立預金", th: "บัญชีออมทรัพย์แบบยืดหยุ่นสำหรับชาวต่างชาติ ยืนยันคุณสมบัติและวงเงินรายเดือนจากเอกสารอธิบายผลิตภัณฑ์อย่างเป็นทางการ" },
    publicConditions: { en: "Real-name foreign residents, non-residents excluded, one account per person, KRW 1,000 to 3,000,000 per month", vi: "Người nước ngoài cư trú có danh tính thật, loại trừ người không cư trú, mỗi người một tài khoản, từ 1.000 đến 3.000.000 KRW mỗi tháng", zh: "实名外国人，排除非居住者，1 人 1 账户，每月 1 千至 300 万韩元", ja: "実名の外国人、非居住者を除く、1人1口座、毎月1千ウォン以上300万ウォン以下", th: "ชาวต่างชาติที่ยืนยันตัวตนจริง ไม่รวมผู้ไม่มีถิ่นที่อยู่ 1 คน 1 บัญชี เดือนละ 1,000 ถึง 3,000,000 วอน" },
    additionalConditions: { en: "Identity verification and the actual contract terms need final confirmation from Shinhan Bank", vi: "Xác minh danh tính và nội dung hợp đồng thực tế cần Ngân hàng Shinhan xác nhận cuối cùng", zh: "实名确认与实际合同内容需新韩银行最终确认", ja: "実名確認と実際の契約内容は新韓銀行の最終確認が必要です", th: "การยืนยันตัวตนและเงื่อนไขสัญญาจริงต้องได้รับการยืนยันขั้นสุดท้ายจากธนาคารชินฮัน" },
    requiredDocuments: { en: "The official product manual does not publish a document list, so the bank must confirm it", vi: "Bản mô tả sản phẩm chính thức không công bố danh sách giấy tờ nên cần ngân hàng xác nhận", zh: "官方产品说明书未公开提交材料清单，需向银行确认", ja: "公式商品説明書に提出書類一覧が公開されていないため、銀行の確認が必要です", th: "เอกสารอธิบายผลิตภัณฑ์อย่างเป็นทางการไม่ได้เปิดเผยรายการเอกสาร จึงต้องให้ธนาคารยืนยัน" },
    applicationMethod: { en: "Apply through an official Shinhan Bank channel after checking the product manual and the actual contract terms", vi: "Đăng ký qua kênh chính thức của Ngân hàng Shinhan sau khi xem bản mô tả sản phẩm và nội dung hợp đồng thực tế", zh: "在新韩银行官方渠道确认产品说明书与实际合同内容后申请", ja: "新韓銀行の公式チャネルで商品説明書と実際の契約内容を確認のうえ申し込み", th: "สมัครผ่านช่องทางอย่างเป็นทางการของธนาคารชินฮันหลังตรวจสอบเอกสารผลิตภัณฑ์และเงื่อนไขสัญญาจริง" },
    sourceTitle: { en: "SOL Global Savings official product manual", vi: "Bản mô tả sản phẩm chính thức SOL Global Savings", zh: "SOL 全球零存整取官方产品说明书", ja: "SOLグローバル積立預金 公式商品説明書", th: "เอกสารอธิบายผลิตภัณฑ์อย่างเป็นทางการของ SOL Global Savings" },
  },
  "SHINHAN-SOL-GLOBAL-JEONSE": {
    description: { en: "Only the existence of this product is confirmed from a supporting official document. The direct product manual and eligibility sources have not been secured.", vi: "Chỉ xác nhận được sự tồn tại của sản phẩm từ tài liệu chính thức hỗ trợ. Chưa có bản mô tả sản phẩm trực tiếp và nguồn điều kiện đăng ký.", zh: "仅从官方辅助资料确认该产品存在，尚未取得直接的产品说明书与加入条件来源。", ja: "公式の補助資料から商品の存在のみが確認されており、直接の商品説明書と加入条件ソースは未確保です。", th: "ยืนยันได้เพียงว่ามีผลิตภัณฑ์นี้อยู่จากเอกสารอย่างเป็นทางการประกอบ ยังไม่มีเอกสารอธิบายผลิตภัณฑ์โดยตรงและแหล่งข้อมูลเงื่อนไขการสมัคร" },
    publicConditions: { en: "Official eligibility sources have not been secured", vi: "Chưa có nguồn điều kiện đăng ký chính thức", zh: "尚未取得官方加入条件来源", ja: "公式の加入条件ソースが未確保です", th: "ยังไม่มีแหล่งข้อมูลเงื่อนไขการสมัครอย่างเป็นทางการ" },
    additionalConditions: { en: "Because no direct product manual or terms are registered, eligibility, identity verification, channels, and required documents all need bank confirmation", vi: "Vì chưa đăng ký bản mô tả sản phẩm hay điều khoản trực tiếp, điều kiện đăng ký, xác minh danh tính, kênh và giấy tờ đều cần ngân hàng xác nhận", zh: "由于未登记直接的产品说明书与条款，加入条件、实名确认、渠道及所需材料均需向银行确认", ja: "直接の商品説明書・約款が登録されていないため、加入条件・本人確認・チャネル・必要書類はいずれも銀行の確認が必要です", th: "เนื่องจากยังไม่มีการลงทะเบียนเอกสารผลิตภัณฑ์หรือข้อกำหนดโดยตรง เงื่อนไขการสมัคร การยืนยันตัวตน ช่องทาง และเอกสารที่ต้องใช้ ล้วนต้องให้ธนาคารยืนยัน" },
    requiredDocuments: { en: "This cannot be confirmed from the official materials registered so far", vi: "Không thể xác nhận chỉ với tài liệu chính thức đã đăng ký hiện tại", zh: "仅凭目前登记的官方资料无法确认", ja: "現在登録されている公式資料だけでは確認できません", th: "ไม่สามารถยืนยันได้จากเอกสารอย่างเป็นทางการที่ลงทะเบียนไว้ในขณะนี้" },
    applicationMethod: { en: "First check with a Shinhan Bank branch or the official call centre whether the product is sold and what the application process is", vi: "Trước tiên hãy hỏi chi nhánh Ngân hàng Shinhan hoặc tổng đài chính thức về việc sản phẩm có được bán không và quy trình đăng ký", zh: "请先向新韩银行营业网点或官方客服中心确认该产品是否销售及申请流程", ja: "まず新韓銀行の店舗または公式カスタマーセンターで、商品の販売有無と申請手続きをご確認ください", th: "กรุณาสอบถามสาขาธนาคารชินฮันหรือศูนย์บริการลูกค้าอย่างเป็นทางการก่อนว่ามีการขายผลิตภัณฑ์นี้หรือไม่ และขั้นตอนการสมัครเป็นอย่างไร" },
    sourceTitle: { en: "Supporting reference to the jeonse loan inside the SOL Global Savings product manual", vi: "Căn cứ tham khảo về khoản vay jeonse trong bản mô tả sản phẩm SOL Global Savings", zh: "SOL 全球零存整取产品说明书内关于全租房贷款的辅助依据", ja: "SOLグローバル積立預金 商品説明書内のチョンセ融資に関する補助根拠", th: "การอ้างอิงประกอบเกี่ยวกับสินเชื่อชอนเซในเอกสารผลิตภัณฑ์ SOL Global Savings" },
  },
  "KBSEC-FOREIGN-STOCK": {
    description: { en: "An investment service that compares the published nationality conditions for foreign residents, based on the official KB Securities overseas-stock guide", vi: "Dịch vụ đầu tư so sánh điều kiện quốc tịch được công bố cho người nước ngoài cư trú, dựa trên hướng dẫn cổ phiếu nước ngoài chính thức của KB Securities", zh: "依据 KB 证券官方海外股票指引，比较居住外国人国籍公开条件的投资服务", ja: "KB証券の公式海外株式案内に基づき、居住外国人の国籍公開条件を比較する投資サービス", th: "บริการลงทุนที่เปรียบเทียบเงื่อนไขสัญชาติที่เปิดเผยสำหรับชาวต่างชาติที่พำนัก ตามคู่มือหุ้นต่างประเทศอย่างเป็นทางการของ KB Securities" },
    publicConditions: { en: "Available to foreign residents, excluding US and Canadian nationals", vi: "Dành cho người nước ngoài cư trú, không bao gồm công dân Mỹ và Canada", zh: "居住外国人可用，排除美国・加拿大国籍", ja: "居住外国人は利用可能、米国・カナダ国籍は除く", th: "ใช้ได้สำหรับชาวต่างชาติที่พำนัก ยกเว้นผู้ถือสัญชาติสหรัฐฯ และแคนาดา" },
    additionalConditions: { en: "Account-opening identity verification and the suitability check follow KB Securities procedures", vi: "Xác minh danh tính khi mở tài khoản và kiểm tra tính phù hợp theo quy trình của KB Securities", zh: "开户本人确认与交易适合性确认依 KB 证券流程办理", ja: "口座開設時の本人確認と取引適合性の確認はKB証券の手続きに従います", th: "การยืนยันตัวตนเมื่อเปิดบัญชีและการตรวจสอบความเหมาะสมเป็นไปตามขั้นตอนของ KB Securities" },
    requiredDocuments: { en: "Consent to overseas-stock investment risk and to the provision of customer information", vi: "Đồng ý về rủi ro đầu tư cổ phiếu nước ngoài và việc cung cấp thông tin khách hàng", zh: "海外股票投资风险及客户信息提供同意书", ja: "海外株式投資リスクおよび顧客情報提供に関する同意", th: "การให้ความยินยอมเรื่องความเสี่ยงการลงทุนหุ้นต่างประเทศและการให้ข้อมูลลูกค้า" },
    applicationMethod: { en: "Open a comprehensive brokerage account, then deposit and exchange currency, place overseas-stock orders, and handle taxes", vi: "Mở tài khoản môi giới tổng hợp, sau đó nạp tiền và đổi ngoại tệ, đặt lệnh cổ phiếu nước ngoài và xử lý thuế", zh: "开立综合委托账户后进行入金・换汇、海外股票下单与税务处理", ja: "総合委託口座を開設後、入金・両替、海外株式の注文、税務処理を行います", th: "เปิดบัญชีนายหน้าแบบรวม จากนั้นฝากเงินและแลกเปลี่ยนสกุลเงิน ส่งคำสั่งซื้อขายหุ้นต่างประเทศ และจัดการภาษี" },
    sourceTitle: { en: "KB Securities overseas stock trading guide", vi: "Hướng dẫn giao dịch cổ phiếu nước ngoài của KB Securities", zh: "KB证券海外股票买卖指引", ja: "KB証券 海外株式 売買案内", th: "คู่มือการซื้อขายหุ้นต่างประเทศของ KB Securities" },
  },
};

export function productDetailLabel(
  locale: Locale,
  productCode: string,
  field: ProductDetailField,
  storedValue: string,
): string {
  if (locale === "ko") return storedValue;
  return details[productCode]?.[field]?.[locale] ?? storedValue;
}
